idle:
  air_temperature: { base: 295, noise: 0.2 }
  process_temperature: { base: 298, noise: 0.3 }
  rotational_speed: { base: 0, noise: 2 }
  torque: { base: 0, noise: 0.1 }
  tool_wear: { base: 0, noise: 0 }
  machine_failure: 0

startup:
  air_temperature: { base: 296, noise: 0.5 }
  process_temperature: { base: 303, noise: 0.6 }
  rotational_speed: { base: 1000, noise: 50 }
  torque: { base: 15, noise: 3 }
  tool_wear: { base: 5, noise: 1 }
  machine_failure: 0

steady_state:
  air_temperature: { base: 300, noise: 0.4 }
  process_temperature: { base: 310, noise: 0.7 }
  rotational_speed: { base: 1600, noise: 25 }
  torque: { base: 40, noise: 5 }
  tool_wear: { base: 20, noise: 2 }
  machine_failure: 0

degrading:
  air_temperature: { base: 305, noise: 1.0 }
  process_temperature: { base: 318, noise: 1.2 }
  rotational_speed: { base: 1550, noise: 40 }
  torque: { base: 55, noise: 6 }
  tool_wear: { base: 80, noise: 3 }
  machine_failure: 0

failure:
  air_temperature: { base: 310, noise: 2.5 }
  process_temperature: { base: 325, noise: 3 }
  rotational_speed: { base: 1400, noise: 80 }
  torque: { base: 70, noise: 10 }
  tool_wear: { base: 100, noise: 5 }
  machine_failure: 1
